# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-18 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('actual_name', models.CharField(max_length=20)),
                ('convertion_rate', models.DecimalField(decimal_places=8, default=1.0, max_digits=32)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
