# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-30 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizingBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Planet'), (1, 'Moon'), (2, 'Asteroid'), (3, 'Artificial Body'), (4, 'Others')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('docking_tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpacePort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Domestic'), (1, 'Interplanetary'), (2, 'Interstellar'), (3, 'Intergalactic')], default=1)),
                ('authorizing_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celestria.AuthorizingBody')),
            ],
        ),
    ]
