# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-01 07:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('celestria', '0001_authorizing_body_spaceport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('user_type', models.IntegerField(choices=[(0, 'Customer'), (1, 'Staff')], default=0)),
                ('password_reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('password_reset_expiration', models.DateTimeField(blank=True, null=True)),
                ('registered_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celestria.AuthorizingBody')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
