# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-02 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celestria', '0004_spacecraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
                ('estimated_departure_time', models.DateTimeField()),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival_time', models.DateTimeField()),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.TimeField()),
                ('status', models.IntegerField(choices=[(0, 'On Hold'), (1, 'Boarding'), (2, 'Travelling'), (3, 'Arrived'), (3, 'Cancelled')], default=0)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True)),
                ('destination_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_space_flights', to='celestria.SpacePort')),
                ('originating_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_space_flights', to='celestria.SpacePort')),
            ],
        ),
    ]
