# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-04 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celestria', '0005_spaceflight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_position', models.CharField(max_length=255)),
                ('employed_on', models.DateTimeField()),
                ('resigned_on', models.DateTimeField(blank=True, null=True)),
                ('rank', models.IntegerField(choices=[(1, 'Regular'), (2, 'Supervisor'), (3, 'Manager'), (4, 'Captain'), (5, 'Executive')], default=1)),
                ('account_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='celestria.AccountProfile')),
            ],
        ),
    ]
