# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-11 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('celestria', '0006_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
