# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-11 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celestria', '0007_accountprofile_registered_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Regular'), (2, 'Premium')], default=1)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('account_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='celestria.AccountProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='spaceflight',
            name='status',
            field=models.IntegerField(choices=[(0, 'On Hold'), (1, 'Boarding'), (2, 'Travelling'), (3, 'Arrived'), (4, 'Cancelled')], default=0),
        ),
    ]
