# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-04 03:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('celestria', '0009_extend_from_logged_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=250, unique=True)),
                ('seat_number', models.CharField(max_length=64)),
                ('status', models.IntegerField(choices=[(0, 'Selling'), (1, 'Reserved'), (2, 'Boarded'), (3, 'Cancelled'), (4, 'Refunded')], default=0)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True)),
                ('sold_on', models.DateTimeField(blank=True, null=True)),
                ('boarded_on', models.DateTimeField(blank=True, null=True)),
                ('cancelled_on', models.DateTimeField(blank=True, null=True)),
                ('refunded_on', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='celestria.SpaceFlight')),
                ('sold_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_bought', to='celestria.AccountProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
